name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What would you like to add/change?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Why is this useful? Any alternatives?
    validations:
      required: false

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What files/areas would likely change?
    validations:
      required: false
